apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tkc-app
  namespace: argocd
spec:
  destination:
    server: https://10.117.11.2:6443 #cluster supervisor
  project: default
#  syncPolicy:
#    automated:
#      prune: false
#      selfHeal: false
  source:
    path: tkc-config
    repoURL: https://github.com/albertovmware/gitops-tkgs.git
    targetRevision: HEAD%
